Repository openshift/managed-notifications, pull requests merged in 2024-02, with the labels that each got.

#290 OSD-19763: Updated correct attributes to hcp, ocm and cluster managed notifications
  hcp/OCPBUGS_14611_Leftover_PersistentVolume.json
Labels: approved, lgtm, jira/valid-reference

#291 Adding SL for worker nodes stopped manually in DataPlane for Hosted clusters
  hcp/WorkerNodes_Stopped_error.json
Labels: approved, lgtm

#294 remove efs operator service log as it is no longer supported
  osd/aws/MultipleVersionsOfEFSOperatorInstalled.json
Labels: approved, lgtm

#295 CIDR should be parameterised
  osd/InvalidCIDR.json
Labels: approved, lgtm

#292 Update incident service logs
  osd/incident_declared.json
  osd/incident_resolved.json
  osd/incident_update.json
Labels: approved, lgtm

#293 fix link for invalid subnet SL
  osd/aws/InstallFailed_InvalidSubnet.json
  osd/aws/InstallFailed_STS_PrivateLink.json
Labels: approved, lgtm

#297 Expanding EIP acronym to Elastic IP
  osd/aws/AddressLimitExceeded.json
Labels: approved, lgtm

#302 Fixed broken links
  osd/aws/InstallFailed_CreateServiceLinkedRole.json
  osd/rosa_clusterlogging_general.json
Labels: approved, lgtm

#287 Update InstallFailed_proxy_unreachable.json
  osd/aws/InstallFailed_proxy_unreachable.json
Labels: tide/merge-method-squash, approved, lgtm

#301 Remove duplicate _tags and update SOP backrefs
  osd/User_Forbidden.json
  osd/aws/InstallFailed_InvalidCustomTag.json
  osd/aws/ROSA_AWS_KMS_permissions_required.json
  osd/cluster-wide_proxy_ca_expiring.json
  osd/cluster_cannot_be_recovered.json
  osd/cluster_has_gone_missing.json
  osd/customer_modified_worker_nodes.json
  osd/invalid_iaas_credentials.json
  osd/rosa_customer_pdb_preventing_drain.json
  osd/validating_webhook_configurations.json
  osd/workernode_overloaded.json
  osd/workload_deployed_in_restricted_project.json
Labels: approved, lgtm

#298 Adds AllowedSourceRanges servicelog.
  osd/AllowedSourceRanges.json
Labels: approved, lgtm
